version: '3.1'

services: 
  db:
    container_name: db_test
    image: postgres
    restart: always
    ports: 
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'test'
    volumes:
      - ./db_test:/var/lib/postgresql/data

  app:
    container_name: app_test
    build: ./app
    command: ["./wait_for_it.sh", "db:5433", "--", "npm", "run", "test"]
    depends_on:
      - db
    environment:
      - DB_HOST=db
    restart: on-failure
    ports:
      - "3001:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/app/
      - /home/app/node_modules